CREATE TABLE MEMBER(
    ID VARCHAR2(20) NOT NULL PRIMARY KEY,
    PSWD VARCHAR2(16) NOT NULL,
    NAME VARCHAR2(40) NOT NULL,
    SEX VARCHAR2(1) NOT NULL,
    BIRTHDAY DATE NOT NULL,
    EMAIL VARCHAR2(50) NOT NULL UNIQUE,
    MOB_NO VARCHAR2(16) NOT NULL
);

CREATE TABLE ITEM(
    ITEM_CODE NUMBER(4) NOT NULL PRIMARY KEY,
    ITEM_NAME VARCHAR2(50) NOT NULL,
    ITEM_COUNT NUMBER(3),
    ITEM_PRICE NUMBER(7)
);

CREATE TABLE ORDERS(
    ORDER_CODE NUMBER NOT NULL CONSTRAINT ORDER_ORDERCODE_PK PRIMARY KEY,
    ID VARCHAR2(20) CONSTRAINT ORDER_MEMBER_ID_FK REFERENCES MEMBER(ID),
    ITEM_CODE NUMBER(4) CONSTRAINT ORDERS_ITEM_ITEMCODE_FK REFERENCES ITEM(ITEM_CODE),
    ITEM_ORDER_COUNT NUMBER(3),
    TOTAL_PRICE NUMBER(8),
    ORDER_DATE DATE NOT NULL,
    ORDER_CHECK VARCHAR2(1)  DEFAULT 'N' CHECK(ORDER_CHECK IN ('Y','N')) NOT NULL 
);


SELECT * 
FROM USER_CONSTRAINTS
WHERE TABLE_NAME IN ('MEMBER','ITEM','ORDERS');

13. 아이디: KUH, 비밀번호: KUH, 이름: 권유화, 성별: F, 생일: 19870930, 이메일: kuh@naver.com, 휴대전화번호: 01055556666 (4점)	

14. 아이디: JMG, 비밀번호: JMG, 이름: 전민균, 성별: M, 생일: 19741011, 이메일: jmg@hankyung.com, 휴대전화번호: 01012123434 (4점)

INSERT INTO MEMBER
VALUES('CHO','CHO','조현석','M','19921212','chs@naver.com','01041782102');

INSERT INTO MEMBER
VALUES('KUH','KUH','권유화','F','19870930','kuh@naver.com','01055556666');

INSERT INTO MEMBER
VALUES('JMG','JMG','전민균','M','19741011','jmg@hankyung.com','01012123434');

SELECT * FROM MEMBER;

CREATE SEQUENCE ITEM_ITEMCODE_SEQ
    START WITH 1
INCREMENT BY 1
MAXVALUE 9999;

INSERT INTO ITEM
VALUES(ITEM_ITEMCODE_SEQ.NEXTVAL, 'Memory', 400, 31400);

INSERT INTO ITEM
VALUES(ITEM_ITEMCODE_SEQ.NEXTVAL, 'Hard-Disk', 200, 57000 );

SELECT * FROM ITEM;

DESC ORDERS;

INSERT INTO ORDERS
VALUES(1,'CHS',1,10,314000,SYSDATE,'Y');

INSERT INTO ORDERS
VALUES(2,'CHS',2,10,570000,SYSDATE,'N');

SELECT * FROM ORDERS;

DESC ITEM;

-- 트랜잭션
UPDATE ITEM SET ITEM_COUNT = ITEM_COUNT - (SELECT ITEM_ORDER_COUNT
                                              FROM ORDERS
                                             WHERE ORDER_CHECK = 'Y'
                                               AND ORDER_CODE = 3)
WHERE ITEM_CODE = (SELECT ITEM_CODE
                    FROM ORDERS
                    WHERE ORDER_CODE = 3);
COMMIT;                    
--                                               
         