--------------------------------------------------------
--  파일이 생성됨 - 수요일-10월-19-2022   
--------------------------------------------------------
DROP SEQUENCE "EZEN"."MEMBERS_MNO_SEQ";
DROP SEQUENCE "EZEN"."MEMBER_MNO_SEQ";
DROP SEQUENCE "EZEN"."TB_FILE_IDX_SEQ";
DROP TABLE "EZEN"."MEMBER";
DROP TABLE "EZEN"."TB_FILE";
--------------------------------------------------------
--  DDL for Sequence MEMBERS_MNO_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "EZEN"."MEMBERS_MNO_SEQ"  MINVALUE 1 MAXVALUE 99999 INCREMENT BY 1 START WITH 137 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence MEMBER_MNO_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "EZEN"."MEMBER_MNO_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 360 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence TB_FILE_IDX_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "EZEN"."TB_FILE_IDX_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 101 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Table MEMBER
--------------------------------------------------------

  CREATE TABLE "EZEN"."MEMBER" 
   (	"MNO" NUMBER, 
	"EMAIL" VARCHAR2(40 BYTE), 
	"PWD" VARCHAR2(100 BYTE), 
	"MNAME" VARCHAR2(50 BYTE), 
	"CRE_DATE" DATE, 
	"MOD_DATE" DATE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;

   COMMENT ON COLUMN "EZEN"."MEMBER"."MNO" IS '회원번호';
   COMMENT ON COLUMN "EZEN"."MEMBER"."EMAIL" IS '이메일';
   COMMENT ON COLUMN "EZEN"."MEMBER"."PWD" IS '비밀번호';
   COMMENT ON COLUMN "EZEN"."MEMBER"."MNAME" IS '이름';
   COMMENT ON COLUMN "EZEN"."MEMBER"."CRE_DATE" IS '가입일';
   COMMENT ON COLUMN "EZEN"."MEMBER"."MOD_DATE" IS '마지막암호변경일';
   COMMENT ON TABLE "EZEN"."MEMBER"  IS '회원기본정보';
--------------------------------------------------------
--  DDL for Table TB_FILE
--------------------------------------------------------

  CREATE TABLE "EZEN"."TB_FILE" 
   (	"IDX" NUMBER, 
	"PARENT_SEQ" NUMBER, 
	"ORIGINAL_FILE_NAME" VARCHAR2(260 BYTE), 
	"STORED_FILE_NAME" VARCHAR2(36 BYTE), 
	"FILE_SIZE" NUMBER, 
	"CRE_DATE" DATE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
REM INSERTING into EZEN.MEMBER
SET DEFINE OFF;
Insert into EZEN.MEMBER (MNO,EMAIL,PWD,MNAME,CRE_DATE,MOD_DATE) values (1,'s1@test.com','1234','홍길동',to_date('22/10/13','RR/MM/DD'),to_date('22/10/14','RR/MM/DD'));
Insert into EZEN.MEMBER (MNO,EMAIL,PWD,MNAME,CRE_DATE,MOD_DATE) values (2,'s2@test.com','1234','임꺽정',to_date('22/09/16','RR/MM/DD'),to_date('22/09/16','RR/MM/DD'));
Insert into EZEN.MEMBER (MNO,EMAIL,PWD,MNAME,CRE_DATE,MOD_DATE) values (3,'s3@test.com','1234','일지매',to_date('22/09/16','RR/MM/DD'),to_date('22/10/14','RR/MM/DD'));
Insert into EZEN.MEMBER (MNO,EMAIL,PWD,MNAME,CRE_DATE,MOD_DATE) values (4,'s4@test.com','1234','이몽룡',to_date('22/09/16','RR/MM/DD'),to_date('22/10/14','RR/MM/DD'));
Insert into EZEN.MEMBER (MNO,EMAIL,PWD,MNAME,CRE_DATE,MOD_DATE) values (5,'s5@test.com','1234','성춘향',to_date('22/09/16','RR/MM/DD'),to_date('22/10/14','RR/MM/DD'));
Insert into EZEN.MEMBER (MNO,EMAIL,PWD,MNAME,CRE_DATE,MOD_DATE) values (10,'1234@연습용','1234','연습용회원1',to_date('22/09/16','RR/MM/DD'),to_date('22/09/21','RR/MM/DD'));
Insert into EZEN.MEMBER (MNO,EMAIL,PWD,MNAME,CRE_DATE,MOD_DATE) values (128,'상어@상어','1234','이순신상어51',to_date('22/10/11','RR/MM/DD'),to_date('22/10/17','RR/MM/DD'));
Insert into EZEN.MEMBER (MNO,EMAIL,PWD,MNAME,CRE_DATE,MOD_DATE) values (129,'kaver.com','1234','이영현석',to_date('22/10/11','RR/MM/DD'),to_date('22/10/17','RR/MM/DD'));
Insert into EZEN.MEMBER (MNO,EMAIL,PWD,MNAME,CRE_DATE,MOD_DATE) values (13,'last@test.com','1234','마지막회원5',to_date('22/09/16','RR/MM/DD'),to_date('22/10/11','RR/MM/DD'));
Insert into EZEN.MEMBER (MNO,EMAIL,PWD,MNAME,CRE_DATE,MOD_DATE) values (268,'dfadhadh','adhadhdafh','sdaafgha',to_date('22/10/13','RR/MM/DD'),to_date('22/10/13','RR/MM/DD'));
Insert into EZEN.MEMBER (MNO,EMAIL,PWD,MNAME,CRE_DATE,MOD_DATE) values (319,'fsfsj','sfjsfsfj','dahghgsh',to_date('22/10/18','RR/MM/DD'),to_date('22/10/18','RR/MM/DD'));
Insert into EZEN.MEMBER (MNO,EMAIL,PWD,MNAME,CRE_DATE,MOD_DATE) values (321,'다른사람@mail.com','1','다른사람1',to_date('22/10/18','RR/MM/DD'),to_date('22/10/18','RR/MM/DD'));
Insert into EZEN.MEMBER (MNO,EMAIL,PWD,MNAME,CRE_DATE,MOD_DATE) values (238,'hs_4naver.com','1234','현석_4',to_date('22/10/16','RR/MM/DD'),to_date('22/10/12','RR/MM/DD'));
Insert into EZEN.MEMBER (MNO,EMAIL,PWD,MNAME,CRE_DATE,MOD_DATE) values (239,'hs_5naver.com','1234','현석_5',to_date('22/10/17','RR/MM/DD'),to_date('22/10/12','RR/MM/DD'));
Insert into EZEN.MEMBER (MNO,EMAIL,PWD,MNAME,CRE_DATE,MOD_DATE) values (269,'dfgdhaghfas','hfshshfh','hdhahfdh',to_date('22/10/13','RR/MM/DD'),to_date('22/10/13','RR/MM/DD'));
Insert into EZEN.MEMBER (MNO,EMAIL,PWD,MNAME,CRE_DATE,MOD_DATE) values (241,'hs_7naver.com','1234','현석_7',to_date('22/10/19','RR/MM/DD'),to_date('22/10/12','RR/MM/DD'));
Insert into EZEN.MEMBER (MNO,EMAIL,PWD,MNAME,CRE_DATE,MOD_DATE) values (320,'sfghgfshsfhsf','144444','shhsfhgf',to_date('22/10/18','RR/MM/DD'),to_date('22/10/18','RR/MM/DD'));
Insert into EZEN.MEMBER (MNO,EMAIL,PWD,MNAME,CRE_DATE,MOD_DATE) values (243,'hs_9naver.com','1234','현석_9',to_date('22/10/21','RR/MM/DD'),to_date('22/10/17','RR/MM/DD'));
Insert into EZEN.MEMBER (MNO,EMAIL,PWD,MNAME,CRE_DATE,MOD_DATE) values (244,'hs_10naver.com','1234','현석_10',to_date('22/10/22','RR/MM/DD'),to_date('22/10/12','RR/MM/DD'));
Insert into EZEN.MEMBER (MNO,EMAIL,PWD,MNAME,CRE_DATE,MOD_DATE) values (322,'이미자닷컴','12341234','이미자',to_date('22/10/18','RR/MM/DD'),to_date('22/10/18','RR/MM/DD'));
Insert into EZEN.MEMBER (MNO,EMAIL,PWD,MNAME,CRE_DATE,MOD_DATE) values (246,'hs_12naver.com','1234','현석_12sdgfdg',to_date('22/10/24','RR/MM/DD'),to_date('22/10/14','RR/MM/DD'));
Insert into EZEN.MEMBER (MNO,EMAIL,PWD,MNAME,CRE_DATE,MOD_DATE) values (247,'hs_13naver.com','1234','현석_13AB',to_date('22/10/25','RR/MM/DD'),to_date('22/10/14','RR/MM/DD'));
Insert into EZEN.MEMBER (MNO,EMAIL,PWD,MNAME,CRE_DATE,MOD_DATE) values (340,'123sojin@test','12','소진이23984',to_date('22/10/19','RR/MM/DD'),to_date('22/10/19','RR/MM/DD'));
Insert into EZEN.MEMBER (MNO,EMAIL,PWD,MNAME,CRE_DATE,MOD_DATE) values (249,'hs_15naver.com','1234','현석_15dasd',to_date('22/10/27','RR/MM/DD'),to_date('22/10/14','RR/MM/DD'));
Insert into EZEN.MEMBER (MNO,EMAIL,PWD,MNAME,CRE_DATE,MOD_DATE) values (250,'hs_16naver.com','1234','현석_16fdgdg',to_date('22/10/28','RR/MM/DD'),to_date('22/10/14','RR/MM/DD'));
Insert into EZEN.MEMBER (MNO,EMAIL,PWD,MNAME,CRE_DATE,MOD_DATE) values (251,'hs_17naver.com','1234','현석_17dsfgfdg',to_date('22/10/29','RR/MM/DD'),to_date('22/10/14','RR/MM/DD'));
Insert into EZEN.MEMBER (MNO,EMAIL,PWD,MNAME,CRE_DATE,MOD_DATE) values (252,'hs_18naver.com','1234','현석_18체인지',to_date('22/10/30','RR/MM/DD'),to_date('22/10/14','RR/MM/DD'));
Insert into EZEN.MEMBER (MNO,EMAIL,PWD,MNAME,CRE_DATE,MOD_DATE) values (270,'rdashadhjajfgs','jsfjsgfjsfgj','ewarghardh',to_date('22/10/13','RR/MM/DD'),to_date('22/10/13','RR/MM/DD'));
Insert into EZEN.MEMBER (MNO,EMAIL,PWD,MNAME,CRE_DATE,MOD_DATE) values (254,'hs_20naver.com','1234','현석_20',to_date('22/11/01','RR/MM/DD'),to_date('22/10/12','RR/MM/DD'));
Insert into EZEN.MEMBER (MNO,EMAIL,PWD,MNAME,CRE_DATE,MOD_DATE) values (255,'30@naver.com','1234','30번은직접',to_date('22/10/12','RR/MM/DD'),to_date('22/10/12','RR/MM/DD'));
Insert into EZEN.MEMBER (MNO,EMAIL,PWD,MNAME,CRE_DATE,MOD_DATE) values (260,'123@naver.com','1234','조현석삼',to_date('22/10/13','RR/MM/DD'),to_date('22/10/14','RR/MM/DD'));
Insert into EZEN.MEMBER (MNO,EMAIL,PWD,MNAME,CRE_DATE,MOD_DATE) values (261,'1234','1234','이영미미',to_date('22/10/13','RR/MM/DD'),to_date('22/10/13','RR/MM/DD'));
Insert into EZEN.MEMBER (MNO,EMAIL,PWD,MNAME,CRE_DATE,MOD_DATE) values (263,'12341234','1234','이영조미',to_date('22/10/13','RR/MM/DD'),to_date('22/10/13','RR/MM/DD'));
Insert into EZEN.MEMBER (MNO,EMAIL,PWD,MNAME,CRE_DATE,MOD_DATE) values (264,'adhfadhdahda','hfadhadfhfdah','dfagfdagd',to_date('22/10/13','RR/MM/DD'),to_date('22/10/13','RR/MM/DD'));
Insert into EZEN.MEMBER (MNO,EMAIL,PWD,MNAME,CRE_DATE,MOD_DATE) values (265,'hshsfhjsfjsfj','ggsfjsjsfjsfj','dsfgsdhsdhgsf',to_date('22/10/13','RR/MM/DD'),to_date('22/10/13','RR/MM/DD'));
Insert into EZEN.MEMBER (MNO,EMAIL,PWD,MNAME,CRE_DATE,MOD_DATE) values (266,'sdfghjsfjsfjfsj','fsjsfjsfjsfjsgfj','shfjfjsfjsf',to_date('22/10/13','RR/MM/DD'),to_date('22/10/13','RR/MM/DD'));
Insert into EZEN.MEMBER (MNO,EMAIL,PWD,MNAME,CRE_DATE,MOD_DATE) values (271,'s14566@test.com','1234','이순신45',to_date('22/10/13','RR/MM/DD'),to_date('22/10/13','RR/MM/DD'));
REM INSERTING into EZEN.TB_FILE
SET DEFINE OFF;
Insert into EZEN.TB_FILE (IDX,PARENT_SEQ,ORIGINAL_FILE_NAME,STORED_FILE_NAME,FILE_SIZE,CRE_DATE) values (32,318,'hjw.jpg','a14a03d21fb549c995123c0c055d7e89.jpg',118442,to_date('22/10/18','RR/MM/DD'));
Insert into EZEN.TB_FILE (IDX,PARENT_SEQ,ORIGINAL_FILE_NAME,STORED_FILE_NAME,FILE_SIZE,CRE_DATE) values (33,319,'intro.txt','011c9f85ef3044509a422d933dc5c256.txt',11,to_date('22/10/18','RR/MM/DD'));
Insert into EZEN.TB_FILE (IDX,PARENT_SEQ,ORIGINAL_FILE_NAME,STORED_FILE_NAME,FILE_SIZE,CRE_DATE) values (34,320,'hjw.jpg','572a955bea9149da8cc472070de41ad5.jpg',118442,to_date('22/10/18','RR/MM/DD'));
Insert into EZEN.TB_FILE (IDX,PARENT_SEQ,ORIGINAL_FILE_NAME,STORED_FILE_NAME,FILE_SIZE,CRE_DATE) values (35,321,'psh.jpg','0a12ba7d241047d0bf5ed56886c6f864.jpg',46298,to_date('22/10/18','RR/MM/DD'));
Insert into EZEN.TB_FILE (IDX,PARENT_SEQ,ORIGINAL_FILE_NAME,STORED_FILE_NAME,FILE_SIZE,CRE_DATE) values (36,321,'test.jpg','f0a2b4d2516f43019437cb723bf7d9d9.jpg',90538,to_date('22/10/18','RR/MM/DD'));
Insert into EZEN.TB_FILE (IDX,PARENT_SEQ,ORIGINAL_FILE_NAME,STORED_FILE_NAME,FILE_SIZE,CRE_DATE) values (42,322,'박주영따봉.jpg','914c7b7946dc4b9ba0dc69eefbc1f179.jpg',263007,to_date('22/10/18','RR/MM/DD'));
Insert into EZEN.TB_FILE (IDX,PARENT_SEQ,ORIGINAL_FILE_NAME,STORED_FILE_NAME,FILE_SIZE,CRE_DATE) values (81,340,'박주영따봉.jpg','c37828f597944fcc8add78b9d519bca2.jpg',263007,to_date('22/10/19','RR/MM/DD'));
Insert into EZEN.TB_FILE (IDX,PARENT_SEQ,ORIGINAL_FILE_NAME,STORED_FILE_NAME,FILE_SIZE,CRE_DATE) values (30,316,'test.jpg','211f8e036cb4493986f13f126db87e8a.jpg',90538,to_date('22/10/18','RR/MM/DD'));
Insert into EZEN.TB_FILE (IDX,PARENT_SEQ,ORIGINAL_FILE_NAME,STORED_FILE_NAME,FILE_SIZE,CRE_DATE) values (31,317,'test.jpg','8bf6c1a584954d9aa1aac7585ae4da93.jpg',90538,to_date('22/10/18','RR/MM/DD'));
--------------------------------------------------------
--  DDL for Index MEMBERS_MNO_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "EZEN"."MEMBERS_MNO_PK" ON "EZEN"."MEMBER" ("MNO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index SYS_C007519
--------------------------------------------------------

  CREATE UNIQUE INDEX "EZEN"."SYS_C007519" ON "EZEN"."TB_FILE" ("IDX") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index MEMBERS_MNO_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "EZEN"."MEMBERS_MNO_PK" ON "EZEN"."MEMBER" ("MNO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index MEMBERS_EMAIL_UK
--------------------------------------------------------

  CREATE UNIQUE INDEX "EZEN"."MEMBERS_EMAIL_UK" ON "EZEN"."MEMBER" ("EMAIL") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index SYS_C007519
--------------------------------------------------------

  CREATE UNIQUE INDEX "EZEN"."SYS_C007519" ON "EZEN"."TB_FILE" ("IDX") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  Constraints for Table MEMBER
--------------------------------------------------------

  ALTER TABLE "EZEN"."MEMBER" ADD CONSTRAINT "MEMBERS_EMAIL_UK" UNIQUE ("EMAIL")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "EZEN"."MEMBER" ADD CONSTRAINT "MEMBERS_MNO_PK" PRIMARY KEY ("MNO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "EZEN"."MEMBER" MODIFY ("MOD_DATE" NOT NULL ENABLE);
  ALTER TABLE "EZEN"."MEMBER" MODIFY ("CRE_DATE" NOT NULL ENABLE);
  ALTER TABLE "EZEN"."MEMBER" MODIFY ("MNAME" NOT NULL ENABLE);
  ALTER TABLE "EZEN"."MEMBER" MODIFY ("PWD" NOT NULL ENABLE);
  ALTER TABLE "EZEN"."MEMBER" MODIFY ("EMAIL" NOT NULL ENABLE);
  ALTER TABLE "EZEN"."MEMBER" MODIFY ("MNO" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table TB_FILE
--------------------------------------------------------

  ALTER TABLE "EZEN"."TB_FILE" ADD PRIMARY KEY ("IDX")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "EZEN"."TB_FILE" MODIFY ("CRE_DATE" NOT NULL ENABLE);
  ALTER TABLE "EZEN"."TB_FILE" MODIFY ("STORED_FILE_NAME" NOT NULL ENABLE);
  ALTER TABLE "EZEN"."TB_FILE" MODIFY ("ORIGINAL_FILE_NAME" NOT NULL ENABLE);
  ALTER TABLE "EZEN"."TB_FILE" MODIFY ("PARENT_SEQ" NOT NULL ENABLE);
